### PR TITLE
ADD: bump version 2.0

### PR DESCRIPTION
**Pull request by kmuehlbauer**
Bump version to 2.0

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
Using deprecation-directive is needed for better results with `sphinx` and the like.

**Comment by kmuehlbauer** [comment]
@pmlandwehr I'm inclined to merge this, but like to hear your opinions. Using V1.2 breaks my `sphinx` workflow on another conda-forge package which is release pending.

**Comment by pmlandwehr** [comment]
Looks good! Thanks for doing the merge.

**Comment by kmuehlbauer** [comment]
@pmlandwehr Upstream was incredibly fast, thanks @briancurtin for the collaboration. So I did not need to patch :+1: and we have v2.0 using deprecation-directive and message_location.

**Pull request merged**
